name: Test Minimal Reusable

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_folder:
        required: true
        type: string
      needs_db:
        required: false
        type: boolean
        default: false

jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - run: echo "hello ${{ inputs.service_name }} ${{ inputs.service_folder }} ${{ inputs.needs_db }}"
