name: Pipeline Test Minimal

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/_test-minimal.yml
    with:
      service_name: etiquetas
      service_folder: servicio-etiquetas
      needs_db: false
    secrets: inherit
